### ISSUE TITLE
New installation not working

### ISSUE THREAD

**Issue by fredfalcon** [PagerDuty/pd-bizops-aether#1]
Installed this on a new instance, getting the following errors when running the start command:

```
ubuntu@ip:~/pd-bizops-aether$ bundle exec aether --config config.yml --secrets secrets.yml --stage production
/home/ubuntu/pd-bizops-aether/lib/aether.rb:1:in `require': /home/ubuntu/pd-bizops-aether/lib/aether/connections.rb:17: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
      salesforce_user:,
                      ^
/home/ubuntu/pd-bizops-aether/lib/aether/connections.rb:83: syntax error, unexpected keyword_end, expecting $end
        from /home/ubuntu/pd-bizops-aether/lib/aether.rb:1:in `<top (required)>'
        from /home/ubuntu/pd-bizops-aether/bin/aether:5:in `require'
        from /home/ubuntu/pd-bizops-aether/bin/aether:5:in `<top (required)>'
        from /var/lib/gems/1.9.1/bin/aether:23:in `load'
        from /var/lib/gems/1.9.1/bin/aether:23:in `<main>'

```

**Comment by fredfalcon** [comment]
A colleague of mine mentioned:

don't you need `key: value` or `:key => value`
not `key:,` for a symbol that isn't defined

I changed all instances of the code that threw a similar error, deleting the colons.  Now getting this:

```
ubuntu@ip:~/pd-bizops-aether$ bundle exec aether --config config.yml --secrets secrets.yml --stage development
/home/ubuntu/pd-bizops-aether/lib/aether/connections.rb:16:in `initialize': wrong number of arguments (1 for 12) (ArgumentError)
        from /home/ubuntu/pd-bizops-aether/bin/aether:27:in `new'
        from /home/ubuntu/pd-bizops-aether/bin/aether:27:in `<top (required)>'
        from /var/lib/gems/1.9.1/bin/aether:23:in `load'
        from /var/lib/gems/1.9.1/bin/aether:23:in `<main>'

```

initialize now looks like this:

```
    def initialize(
      salesforce_user,
      salesforce_password,
      salesforce_client_id,
      salesforce_client_secret,
      salesforce_is_sandbox,
      redshift_user,
      redshift_password,
      redshift_host,
      redshift_port,
      redshift_dbname,
      aws_access_key,
      aws_secret_key)
```
